name: Run OpenAI Script on Commit

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run API script
        run: node js/callopenai.js  # Exécuter le script côté serveur
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
